services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/autocontrol-sanitario
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=autocontrol-sanitario
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: